#!/bin/sh

if test -e /etc/default/endoor ; then
   . /etc/default/endoor
else
   ENDOOR_VICTIM=eth0
   ENDOOR_NETWORK=eth1
fi

sysctl -w net.ipv4.conf.all.forwarding=0
sysctl -w net.ipv6.conf.all.forwarding=0

for net in $ENDOOR_VICTIM $ENDOOR_NETWORK
do
   sysctl -w net.ipv6.conf.$net.autoconf=0
   sysctl -w net.ipv6.conf.$net.accept_ra=0

   iptables -A INPUT -i $net -j DROP
   iptables -A OUTPUT -o $net -j DROP

   ip6tables -A INPUT -i $net -j DROP
   ip6tables -A OUTPUT -o $net -j DROP

   ethtool -K $net gro off
   ethtool -K $net lro off
done

