#!/bin/sh

if test -e /etc/default/endoor ; then
   . /etc/default/endoor
else
   ENDOOR_VICTIM=eth0
   ENDOOR_NETWORK=eth1
fi

sysctl -w net.ipv4.conf.all.forwarding=0
sysctl -w net.ipv6.conf.all.forwarding=0
sysctl -w net.ipv6.conf.$ENDOOR_VICTIM.autoconf=0
sysctl -w net.ipv6.conf.$ENDOOR_NETWORK.accept_ra=0

