#!/bin/sh

VICTIM=eth0
NETWORK=eth1

sysctl -w net.ipv4.conf.all.forwarding=0
sysctl -w net.ipv6.conf.all.forwarding=0
sysctl -w net.ipv6.conf.$VICTIM.autoconf=0
sysctl -w net.ipv6.conf.$NETWORK.accept_ra=0

echo "start with \`./rwpack -i $VICTIM -o $NETWORK\`"

